import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="min-h-screen px-4 py-12 max-w-2xl mx-auto">
      <Link
        href="/"
        className="text-sm underline mb-8 inline-block"
        style={{ color: 'var(--color-text-muted)' }}
      >
        &larr; Back
      </Link>

      <h1
        className="text-3xl font-bold mb-8"
        style={{ color: 'var(--color-text-primary)' }}
      >
        Terms of Service
      </h1>

      <div
        className="space-y-6 text-sm leading-relaxed"
        style={{ color: 'var(--color-text-secondary)' }}
      >
        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            1. About Oath
          </h2>
          <p>
            Oath is a personal growth companion that combines Eastern (Bazi) and
            Western (Astrology) divination traditions with positive psychology
            principles. Content generated by Oath is for entertainment and
            self-reflection purposes only.
          </p>
        </section>

        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            2. No Professional Advice
          </h2>
          <p>
            Oath does not provide medical, financial, legal, or psychological
            advice. Fortune readings and personality analyses are generated
            algorithmically and should not be used as the sole basis for
            important life decisions.
          </p>
        </section>

        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            3. User Accounts
          </h2>
          <p>
            You are responsible for maintaining the security of your account
            credentials. One account per person. Automated or bulk account
            creation is prohibited.
          </p>
        </section>

        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            4. Content Ownership
          </h2>
          <p>
            Your birth data and personal information remain your property. Daily
            fortunes and chart analyses generated for you may be shared via the
            share feature but may not be reproduced commercially without
            permission.
          </p>
        </section>

        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            5. Service Availability
          </h2>
          <p>
            We strive to maintain continuous service but do not guarantee
            uninterrupted availability. Oath may be updated, modified, or
            discontinued with reasonable notice.
          </p>
        </section>

        <section>
          <h2
            className="text-lg font-semibold mb-2"
            style={{ color: 'var(--color-text-primary)' }}
          >
            6. Subscription &amp; Billing
          </h2>
          <p>
            Free tier users receive basic daily fortune readings. Premium
            features (LLM-polished messages, extended history) require a paid
            subscription managed through the platform&apos;s payment system.
          </p>
        </section>

        <p style={{ color: 'var(--color-text-muted)' }}>
          Last updated: February 2026
        </p>
      </div>
    </main>
  );
}
